let items = {
    vase1: {
        id: 1,
        name: 'vase1',
        imagePath: "assets/vase1-{orientation}.png",
        orientation: IsoDom.ORIENTATION_SW,
        price: 100,
        bonus: 0.5,
        size: [1, 1],
        tier: 1,
        images: {
            [IsoDom.ORIENTATION_NW]: {url: 'assets/vase1-1.png', offset: {top: -110, left: -10}},
            [IsoDom.ORIENTATION_NE]: {url: 'assets/vase1-1.png', offset: {top: -110, left: -10}},
            [IsoDom.ORIENTATION_SE]: {url: 'assets/vase1-1.png', offset: {top: -110, left: -10}},
            [IsoDom.ORIENTATION_SW]: {url: 'assets/vase1-1.png', offset: {top: -110, left: -10}},
        },
    },
    vase2: {
        id: 2,
        name: 'vase2',
        imagePath: "assets/vase2-{orientation}.png",
        orientation: IsoDom.ORIENTATION_SW,
        price: 100,
        bonus: 0.5,
        size: [1, 1],
        tier: 5,
        images: {
            [IsoDom.ORIENTATION_NW]: {url: 'assets/vase2-1.png', offset: {top: -150, left: 32}},
            [IsoDom.ORIENTATION_NE]: {url: 'assets/vase2-1.png', offset: {top: -150, left: 32}},
            [IsoDom.ORIENTATION_SE]: {url: 'assets/vase2-1.png', offset: {top: -150, left: 32}},
            [IsoDom.ORIENTATION_SW]: {url: 'assets/vase2-1.png', offset: {top: -150, left: 32}},
        },
    },
    closet1: {
        id: 3,
        name: 'closet1',
        imagePath: "assets/closet1-{orientation}.png",
        orientation: IsoDom.ORIENTATION_SW,
        price: 1000,
        bonus: 1,
        size: [2,1],
        tier: 1,
        images: {
            [IsoDom.ORIENTATION_NW]: {url: 'assets/closet1-1.png', offset: {top: -330, left: -190}},
            [IsoDom.ORIENTATION_NE]: {url: 'assets/closet1-2.png', offset: {top: -330, left: -81}},
            [IsoDom.ORIENTATION_SE]: {url: 'assets/closet1-3.png', offset: {top: -330, left: -190}},
            [IsoDom.ORIENTATION_SW]: {url: 'assets/closet1-4.png', offset: {top: -330, left: -81}},
        }
    },
    small_closet1: {
        id: 4,
        name: 'small_closet1',
        imagePath: "assets/small_closet1-{orientation}.png",
        orientation: IsoDom.ORIENTATION_SW,
        price: 500,
        bonus: 0.5,
        size: [1, 1],
        tier: 2,
        images: {
            [IsoDom.ORIENTATION_NW]: {url: 'assets/small_closet1-1.png', offset: {top: -168, left: -59}},
            [IsoDom.ORIENTATION_NE]: {url: 'assets/small_closet1-2.png', offset: {top: -168, left: -81}},
            [IsoDom.ORIENTATION_SE]: {url: 'assets/small_closet1-3.png', offset: {top: -168, left: -59}},
            [IsoDom.ORIENTATION_SW]: {url: 'assets/small_closet1-4.png', offset: {top: -168, left: -81}},
        }
    },
    couch_blue1: {
        id: 5,
        name: 'couch_blue1',
        imagePath: "assets/couch_blue1-{orientation}.png",
        orientation: IsoDom.ORIENTATION_SW,
        price: 1500,
        bonus: 1.5,
        size: [3, 1],
        tier: 2,
        images: {
            [IsoDom.ORIENTATION_NW]: {url: 'assets/couch_blue1-1.png', offset: {top: -136, left: -284}},
            [IsoDom.ORIENTATION_NE]: {url: 'assets/couch_blue1-2.png', offset: {top: -136, left: -50}},
            [IsoDom.ORIENTATION_SE]: {url: 'assets/couch_blue1-3.png', offset: {top: -136, left: -284}},
            [IsoDom.ORIENTATION_SW]: {url: 'assets/couch_blue1-4.png', offset: {top: -136, left: -50}},
        },
    },
    bench_red1: {
        id: 6,
        name: 'bench_red1',
        imagePath: "assets/bench_red1-{orientation}.png",
        orientation: IsoDom.ORIENTATION_SW,
        price: 800,
        bonus: 0.5,
        size: [2,1],
        tier: 3,
        images: {
            [IsoDom.ORIENTATION_NW]: {url: 'assets/bench_red1-1.png', offset: {top: -80, left: -156}},
            [IsoDom.ORIENTATION_NE]: {url: 'assets/bench_red1-2.png', offset: {top: -81, left: -25}},
            [IsoDom.ORIENTATION_SE]: {url: 'assets/bench_red1-3.png', offset: {top: -80, left: -156}},
            [IsoDom.ORIENTATION_SW]: {url: 'assets/bench_red1-4.png', offset: {top: -81, left: -25}},
        }
    },
    small_bench_red1: {
        id: 7,
        name: 'small_bench_red1',
        imagePath: "assets/small_bench_red1-{orientation}.png",
        orientation: IsoDom.ORIENTATION_SW,
        price: 400,
        bonus: 0.25,
        size: [1, 1],
        tier: 4,
        images: {
            [IsoDom.ORIENTATION_NW]: {url: 'assets/small_bench_red1-1.png', offset: {top: -66, left: -14}},
            [IsoDom.ORIENTATION_NE]: {url: 'assets/small_bench_red1-2.png', offset: {top: -66, left: -14}},
            [IsoDom.ORIENTATION_SE]: {url: 'assets/small_bench_red1-3.png', offset: {top: -66, left: -14}},
            [IsoDom.ORIENTATION_SW]: {url: 'assets/small_bench_red1-4.png', offset: {top: -66, left: -14}},
        },
    },
    meeting_table1: {
        id: 8,
        name: 'meeting_table1',
        imagePath: "assets/meeting_table1-{orientation}.png",
        orientation: IsoDom.ORIENTATION_SW,
        price: 3000,
        bonus: 5,
        size: [3, 6],
        tier: 9,
        images: {
            [IsoDom.ORIENTATION_NE]: {url: 'assets/meeting_table1-1.png', offset: {top: -135, left: -646}},
            [IsoDom.ORIENTATION_NW]: {url: 'assets/meeting_table1-2.png', offset: {top: -128, left: -274}},
            [IsoDom.ORIENTATION_SW]: {url: 'assets/meeting_table1-3.png', offset: {top: -135, left: -646}},
            [IsoDom.ORIENTATION_SE]: {url: 'assets/meeting_table1-4.png', offset: {top: -128, left: -274}},
        }
    },
    table_and_chairs1: {
        id: 9,
        name: 'table_and_chairs1',
        imagePath: "assets/table_and_chairs1-{orientation}.png",
        orientation: IsoDom.ORIENTATION_SW,
        price: 1500,
        bonus: 5,
        size: [4,2],
        tier: 4,
        images: {
            [IsoDom.ORIENTATION_NW]: {url: 'assets/table_and_chairs1-1.png', offset: {top: -74, left: -311}},
            [IsoDom.ORIENTATION_NE]: {url: 'assets/table_and_chairs1-2.png', offset: {top: -73, left: -122}},
            [IsoDom.ORIENTATION_SE]: {url: 'assets/table_and_chairs1-3.png', offset: {top: -97, left: -378}},
            [IsoDom.ORIENTATION_SW]: {url: 'assets/table_and_chairs1-4.png', offset: {top: -103, left: -38}},
        },
    },
    watercooler1: {
        id: 10,
        name: 'watercooler1',
        imagePath: "assets/watercooler1-{orientation}.png",
        orientation: IsoDom.ORIENTATION_SW,
        price: 250,
        bonus: 1,
        size: [1, 1],
        tier: 5,
        images: {
            [IsoDom.ORIENTATION_NW]: {url: 'assets/watercooler1-1.png', offset: {top: -205, left: -39}},
            [IsoDom.ORIENTATION_NE]: {url: 'assets/watercooler1-2.png', offset: {top: -205, left: -39}},
            [IsoDom.ORIENTATION_SE]: {url: 'assets/watercooler1-3.png', offset: {top: -205, left: -39}},
            [IsoDom.ORIENTATION_SW]: {url: 'assets/watercooler1-4.png', offset: {top: -205, left: -39}},
        },
    },
    reception_area1: {
        id: 11,
        name: 'reception_area1',
        imagePath: "assets/reception_area1-{orientation}.png",
        orientation: IsoDom.ORIENTATION_SW,
        price: 2500,
        bonus: 3,
        size: [3, 3],
        tier: 11,
        images: {
            [IsoDom.ORIENTATION_NW]: {url: 'assets/reception_area1-1.png', offset: {top: -47, left: -264}},
            [IsoDom.ORIENTATION_NE]: {url: 'assets/reception_area1-2.png', offset: {top: -47, left: -264}},
            [IsoDom.ORIENTATION_SE]: {url: 'assets/reception_area1-3.png', offset: {top: -47, left: -264}},
            [IsoDom.ORIENTATION_SW]: {url: 'assets/reception_area1-4.png', offset: {top: -47, left: -264}},
        },
    },
    coffe_closet1: {
        id: 12,
        name: 'coffe_closet1',
        imagePath: "assets/coffe_closet1-{orientation}.png",
        orientation: IsoDom.ORIENTATION_SW,
        price: 500,
        bonus: 3,
        size: [1, 1],
        tier: 2,
        images: {
            [IsoDom.ORIENTATION_NW]: {url: 'assets/coffe_closet1-1.png', offset: {top: -178, left: -66}},
            [IsoDom.ORIENTATION_NE]: {url: 'assets/coffe_closet1-2.png', offset: {top: -178, left: -72}},
            [IsoDom.ORIENTATION_SE]: {url: 'assets/coffe_closet1-3.png', offset: {top: -178, left: -66}},
            [IsoDom.ORIENTATION_SW]: {url: 'assets/coffe_closet1-4.png', offset: {top: -178, left: -72}},
        },
    },
    couch_black1: {
        id: 13,
        name: 'couch_black1',
        imagePath: "assets/couch_black1-{orientation}.png",
        orientation: IsoDom.ORIENTATION_SW,
        price: 2000,
        bonus: 2,
        size: [1, 1],
        tier: 8,
        images: {
            [IsoDom.ORIENTATION_NW]: {url: 'assets/couch_black1-1.png', offset: {top: -178, left: -61}},
            [IsoDom.ORIENTATION_NE]: {url: 'assets/couch_black1-2.png', offset: {top: -178, left: -81}},
            [IsoDom.ORIENTATION_SE]: {url: 'assets/couch_black1-3.png', offset: {top: -178, left: -61}},
            [IsoDom.ORIENTATION_SW]: {url: 'assets/couch_black1-4.png', offset: {top: -178, left: -81}},
        }
    },
    couch_black2: {
        id: 14,
        name: 'couch_black2',
        imagePath: "assets/couch_black2-{orientation}.png",
        orientation: IsoDom.ORIENTATION_SW,
        price: 4000,
        bonus: 3,
        size: [2, 1],
        tier: 8,
        images: {
            [IsoDom.ORIENTATION_NW]: {url: 'assets/couch_black2-1.png', offset: {top: -133, left: -208}},
            [IsoDom.ORIENTATION_NE]: {url: 'assets/couch_black2-2.png', offset: {top: -133, left: -70}},
            [IsoDom.ORIENTATION_SE]: {url: 'assets/couch_black2-3.png', offset: {top: -133, left: -208}},
            [IsoDom.ORIENTATION_SW]: {url: 'assets/couch_black2-4.png', offset: {top: -133, left: -70}},
        },
    },
    tv_stand1: {
        id: 15,
        name: 'tv_stand1',
        imagePath: "assets/tv_stand1-{orientation}.png",
        orientation: IsoDom.ORIENTATION_SW,
        price: 1200,
        bonus: 4,
        size: [2, 1],
        tier: 8,
        images: {
            [IsoDom.ORIENTATION_NW]: {url: 'assets/tv_stand1-1.png', offset: {top: -291, left: -80}},
            [IsoDom.ORIENTATION_NE]: {url: 'assets/tv_stand1-2.png', offset: {top: -292, left: 43}},
            [IsoDom.ORIENTATION_SE]: {url: 'assets/tv_stand1-3.png', offset: {top: -291, left: -80}},
            [IsoDom.ORIENTATION_SW]: {url: 'assets/tv_stand1-4.png', offset: {top: -292, left: 43}},
}
    },
    whiteboard2: {
        id: 16,
        name: 'whiteboard2',
        imagePath: "assets/whiteboard2-{orientation}.png",
        orientation: IsoDom.ORIENTATION_SW,
        price: 500,
        bonus: 5,
        size: [2, 1],
        tier: 4,
        images: {
            [IsoDom.ORIENTATION_NW]: {url: 'assets/whiteboard2-1.png', offset: {top: -269, left: -132}},
            [IsoDom.ORIENTATION_NE]: {url: 'assets/whiteboard2-2.png', offset: {top: -273, left: 3}},
            [IsoDom.ORIENTATION_SE]: {url: 'assets/whiteboard2-3.png', offset: {top: -269, left: -132}},
            [IsoDom.ORIENTATION_SW]: {url: 'assets/whiteboard2-4.png', offset: {top: -273, left: 3}},
        }
    },
    glass_wall1: {
        id: 17,
        name: 'glass_wall1',
        imagePath: "assets/glass_wall1-{orientation}.png",
        orientation: IsoDom.ORIENTATION_SW,
        price: 200,
        bonus: 0.1,
        size: [1, 1],
        tier: 1,
        images: {
            [IsoDom.ORIENTATION_NW]: {url: 'assets/glass_wall1-1.png', offset: {top: -424, left: -94}},
            [IsoDom.ORIENTATION_NE]: {url: 'assets/glass_wall1-2.png', offset: {top: -424, left: -90}},
            [IsoDom.ORIENTATION_SE]: {url: 'assets/glass_wall1-3.png', offset: {top: -424, left: -94}},
            [IsoDom.ORIENTATION_SW]: {url: 'assets/glass_wall1-4.png', offset: {top: -424, left: -90}},
        },
    },
    glass_wall_corner1: {
        id: 18,
        name: 'glass_wall_corner1',
        imagePath: "assets/glass_wall_corner1-{orientation}.png",
        orientation: IsoDom.ORIENTATION_SW,
        price: 200,
        bonus: 0.1,
        size: [1, 1],
        tier: 1,
        images: {
            [IsoDom.ORIENTATION_NW]: {url: 'assets/glass_wall_corner1-1.png', offset: {top: -477, left: -93}},
            [IsoDom.ORIENTATION_NE]: {url: 'assets/glass_wall_corner1-2.png', offset: {top: -442, left: -29}},
            [IsoDom.ORIENTATION_SE]: {url: 'assets/glass_wall_corner1-3.png', offset: {top: -408, left: -91}},
            [IsoDom.ORIENTATION_SW]: {url: 'assets/glass_wall_corner1-4.png', offset: {top: -443, left: -154}},
        },
    },
    glass_wall_t1: {
        id: 19,
        name: 'glass_wall_t1',
        imagePath: "assets/glass_wall_t1-{orientation}.png",
        orientation: IsoDom.ORIENTATION_SW,
        price: 200,
        bonus: 0.1,
        size: [1, 1],
        tier: 1,
        images: {
            [IsoDom.ORIENTATION_NW]: {url: 'assets/glass_wall_t1-1.png', offset: {top: -422, left: -91}},
            [IsoDom.ORIENTATION_NE]: {url: 'assets/glass_wall_t1-2.png', offset: {top: -422, left: -92}},
            [IsoDom.ORIENTATION_SE]: {url: 'assets/glass_wall_t1-3.png', offset: {top: -423, left: -91}},
            [IsoDom.ORIENTATION_SW]: {url: 'assets/glass_wall_t1-4.png', offset: {top: -423, left: -95}},
        },
    },
    glass_wall_x1: {
        id: 20,
        name: 'glass_wall_x1',
        imagePath: "assets/glass_wall_x1-{orientation}.png",
        orientation: IsoDom.ORIENTATION_SW,
        price: 200,
        bonus: 0.1,
        size: [1, 1],
        tier: 1,
        images: {
            [IsoDom.ORIENTATION_NW]: {url: 'assets/glass_wall_x1-1.png', offset: {top: -421, left: -92}},
            [IsoDom.ORIENTATION_NE]: {url: 'assets/glass_wall_x1-1.png', offset: {top: -421, left: -92}},
            [IsoDom.ORIENTATION_SE]: {url: 'assets/glass_wall_x1-1.png', offset: {top: -421, left: -92}},
            [IsoDom.ORIENTATION_SW]: {url: 'assets/glass_wall_x1-1.png', offset: {top: -421, left: -92}},
        }
    },
    vending_machine1: {
        id: 21,
        name: 'vending_machine1',
        imagePath: "assets/vending_machine1-{orientation}.png",
        orientation: IsoDom.ORIENTATION_SW,
        price: 800,
        bonus: 4,
        size: [2, 1],
        tier: 7,
        images: {
            [IsoDom.ORIENTATION_NW]: {url: 'assets/vending_machine1-1.png', offset: {top: -331, left: -202}},
            [IsoDom.ORIENTATION_NE]: {url: 'assets/vending_machine1-2.png', offset: {top: -334, left: -77}},
            [IsoDom.ORIENTATION_SE]: {url: 'assets/vending_machine1-3.png', offset: {top: -331, left: -202}},
            [IsoDom.ORIENTATION_SW]: {url: 'assets/vending_machine1-4.png', offset: {top: -334, left: -77}},
        }
    },
    ping_pong_table1: {
        id: 22,
        name: 'ping_pong_table1',
        imagePath: "assets/ping_pong_table1-{orientation}.png",
        orientation: IsoDom.ORIENTATION_SW,
        price: 700,
        bonus: 4,
        size: [4, 2],
        tier: 10,
        images: {
            [IsoDom.ORIENTATION_NW]: {url: 'assets/ping_pong_table1-1.png', offset: {top: -120, left: -350}},
            [IsoDom.ORIENTATION_NE]: {url: 'assets/ping_pong_table1-2.png', offset: {top: -120, left: -130}},
            [IsoDom.ORIENTATION_SE]: {url: 'assets/ping_pong_table1-3.png', offset: {top: -120, left: -350}},
            [IsoDom.ORIENTATION_SW]: {url: 'assets/ping_pong_table1-4.png', offset: {top: -120, left: -130}},
        },
    },
    large_coffee_machine1: {
        id: 23,
        name: 'large_coffee_machine1',
        imagePath: "assets/large_coffee_machine1-{orientation}.png",
        orientation: IsoDom.ORIENTATION_SW,
        price: 5700,
        bonus: 9,
        size: [2, 1],
        tier: 10,
        images: {
            [IsoDom.ORIENTATION_NW]: {url: 'assets/large_coffee_machine1-1.png', offset: {top: -190, left: -160}},
            [IsoDom.ORIENTATION_NE]: {url: 'assets/large_coffee_machine1-2.png', offset: {top: -170, left: -10}},
            [IsoDom.ORIENTATION_SE]: {url: 'assets/large_coffee_machine1-3.png', offset: {top: -190, left: -160}},
            [IsoDom.ORIENTATION_SW]: {url: 'assets/large_coffee_machine1-4.png', offset: {top: -170, left: -10}},
        },
    },
    lounge_chair1: {
        id: 24,
            name: 'lounge_chair1',
    imagePath: "assets/lounge_chair1-{orientation}.png",
    orientation: IsoDom.ORIENTATION_SW,
    price: 1000,
    bonus: 2,
    size: [1, 1],
    tier: 9,
    images: {
    [IsoDom.ORIENTATION_NW]: {url: 'assets/lounge_chair1-1.png', offset: {top: -160, left: -91}},
    [IsoDom.ORIENTATION_NE]: {url: 'assets/lounge_chair1-2.png', offset: {top: -160, left: -101}},
    [IsoDom.ORIENTATION_SE]: {url: 'assets/lounge_chair1-3.png', offset: {top: -187, left: -85}},
            [IsoDom.ORIENTATION_SW]: {url: 'assets/lounge_chair1-4.png', offset: {top: -186, left: -101}},
        },
    },
    wall1: {
        id: 25,
        name: 'wall1',
        imagePath: "assets/wall1-{orientation}.png",
        orientation: IsoDom.ORIENTATION_SW,
        price: 200,
        bonus: 0.1,
        size: [1, 1],
        tier: 8,
        images: {
            [IsoDom.ORIENTATION_NW]: {url: 'assets/wall1-1.png', offset: {top: -424, left: -94}},
            [IsoDom.ORIENTATION_NE]: {url: 'assets/wall1-2.png', offset: {top: -424, left: -90}},
            [IsoDom.ORIENTATION_SE]: {url: 'assets/wall1-3.png', offset: {top: -424, left: -94}},
            [IsoDom.ORIENTATION_SW]: {url: 'assets/wall1-4.png', offset: {top: -424, left: -90}},
        },
    },
    wall_corner1: {
        id: 26,
        name: 'wall_corner1',
        imagePath: "assets/wall_corner1-{orientation}.png",
        orientation: IsoDom.ORIENTATION_SW,
        price: 200,
        bonus: 0.1,
        size: [1, 1],
        tier: 8,
        images: {
            [IsoDom.ORIENTATION_NW]: {url: 'assets/wall_corner1-1.png', offset: {top: -477, left: -93}},
            [IsoDom.ORIENTATION_NE]: {url: 'assets/wall_corner1-2.png', offset: {top: -442, left: -29}},
            [IsoDom.ORIENTATION_SE]: {url: 'assets/wall_corner1-3.png', offset: {top: -408, left: -91}},
            [IsoDom.ORIENTATION_SW]: {url: 'assets/wall_corner1-4.png', offset: {top: -443, left: -154}},
        },
        placementOffset: [
            {top: -569, left: 50},
            {top: -532, left: 110},
            {top: -499, left: 50},
            {top: -534, left: -12},
        ]
    },
    wall_t1: {
        id: 27,
        name: 'wall_t1',
        imagePath: "assets/wall_t1-{orientation}.png",
        orientation: IsoDom.ORIENTATION_SW,
        price: 200,
        bonus: 0.1,
        size: [1, 1],
        tier: 8,
        images: {
            [IsoDom.ORIENTATION_NW]: {url: 'assets/wall_t1-1.png', offset: {top: -422, left: -91}},
            [IsoDom.ORIENTATION_NE]: {url: 'assets/wall_t1-2.png', offset: {top: -422, left: -92}},
            [IsoDom.ORIENTATION_SE]: {url: 'assets/wall_t1-3.png', offset: {top: -423, left: -91}},
            [IsoDom.ORIENTATION_SW]: {url: 'assets/wall_t1-4.png', offset: {top: -423, left: -95}},
        },
    },
    wall_x1: {
        id: 28,
        name: 'wall_x1',
        imagePath: "assets/wall_x1-{orientation}.png",
        orientation: IsoDom.ORIENTATION_SW,
        price: 200,
        bonus: 0.1,
        size: [1, 1],
        tier: 8,
        images: {
            [IsoDom.ORIENTATION_NW]: {url: 'assets/wall_x1-1.png', offset: {top: -421, left: -92}},
            [IsoDom.ORIENTATION_NE]: {url: 'assets/wall_x1-2.png', offset: {top: -421, left: -92}},
            [IsoDom.ORIENTATION_SE]: {url: 'assets/wall_x1-3.png', offset: {top: -421, left: -92}},
            [IsoDom.ORIENTATION_SW]: {url: 'assets/wall_x1-4.png', offset: {top: -421, left: -92}},
        }
    },
};
